Data Loading

In [ ]:
import pandas as pd

In [2]:
nf = pd.read_csv("netflix_titles.csv")

nf.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...

In [3]:
nf.tail(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast..."
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...

In [4]:
nf.info()
nf.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64
 8   rating        7780 non-null   object
 9   duration      7787 non-null   object
 10  listed_in     7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(1), object(11)
memory usage: 730.2+ KB

(7787, 12)

Data Sorting and Cleaning

In [5]:
sorted_nf = nf.sort_values('release_year', ascending = True, kind= 'heapsort', na_position= 'last')
sorted_nf.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
4867,s4868,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...
4960,s4961,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
6117,s6118,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
7342,s7343,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...
7679,s7680,Movie,WWII: Report from the Aleutians,John Huston,NaN,United States,"March 31, 2017",1943,TV-PG,45 min,Documentaries,Filmmaker John Huston narrates this Oscar-nomi...

In [6]:
new_nf = sorted_nf.dropna()

In [7]:
new_nf.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
6117,s6118,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
7268,s7269,Movie,Tunisian Victory,"Frank Capra, John Huston, Hugh Stewart, Roy Bo...",Burgess Meredith,"United States, United Kingdom","March 31, 2017",1944,TV-14,76 min,"Classic Movies, Documentaries",British and American troops join forces to lib...
3425,s3426,Movie,Know Your Enemy - Japan,"Frank Capra, Joris Ivens","Walter Huston, Dana Andrews",United States,"March 31, 2017",1945,TV-14,63 min,"Classic Movies, Documentaries",Though culturally insensitive by modern standa...
3608,s3609,Movie,Let There Be Light,John Huston,Walter Huston,United States,"March 31, 2017",1946,TV-PG,58 min,"Classic Movies, Documentaries",Some returning combat veterans suffer scars th...
7072,s7073,Movie,Thunderbolt,"William Wyler, John Sturges","James Stewart, Lloyd Bridges",United States,"March 31, 2017",1947,TV-PG,42 min,"Classic Movies, Documentaries",A P-47 Thunderbolt squadron is shown in prepar...

In [8]:
new_nf.info()
new_nf.shape

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4808 entries, 6117 to 1285
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       4808 non-null   object
 1   type          4808 non-null   object
 2   title         4808 non-null   object
 3   director      4808 non-null   object
 4   cast          4808 non-null   object
 5   country       4808 non-null   object
 6   date_added    4808 non-null   object
 7   release_year  4808 non-null   int64
 8   rating        4808 non-null   object
 9   duration      4808 non-null   object
 10  listed_in     4808 non-null   object
 11  description   4808 non-null   object
dtypes: int64(1), object(11)
memory usage: 488.3+ KB

(4808, 12)

In [15]:
print(new_nf.duplicated())

6117    False
7268    False
3425    False
3608    False
7072    False
        ...
511     False
7569    False
7551    False
6477    False
1285    False
Length: 4808, dtype: bool

In [17]:
new_nf.drop_duplicates()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
6117,s6118,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
7268,s7269,Movie,Tunisian Victory,"Frank Capra, John Huston, Hugh Stewart, Roy Bo...",Burgess Meredith,"United States, United Kingdom","March 31, 2017",1944,TV-14,76 min,"Classic Movies, Documentaries",British and American troops join forces to lib...
3425,s3426,Movie,Know Your Enemy - Japan,"Frank Capra, Joris Ivens","Walter Huston, Dana Andrews",United States,"March 31, 2017",1945,TV-14,63 min,"Classic Movies, Documentaries",Though culturally insensitive by modern standa...
3608,s3609,Movie,Let There Be Light,John Huston,Walter Huston,United States,"March 31, 2017",1946,TV-PG,58 min,"Classic Movies, Documentaries",Some returning combat veterans suffer scars th...
7072,s7073,Movie,Thunderbolt,"William Wyler, John Sturges","James Stewart, Lloyd Bridges",United States,"March 31, 2017",1947,TV-PG,42 min,"Classic Movies, Documentaries",A P-47 Thunderbolt squadron is shown in prepar...
...,...,...,...,...,...,...,...,...,...,...,...,...
511,s512,Movie,André & his olive tree,Josiah Ng,André Chiang,Singapore,"December 8, 2020",2020,TV-PG,104 min,"Documentaries, International Movies","As he prepares to close his restaurant, Michel..."
7569,s7570,Movie,What Would Sophia Loren Do?,Ross Kauffman,"Nancy ""Vincenza Careri"" Kulik, Sophia Loren",United States,"January 15, 2021",2021,TV-14,32 min,Documentaries,"In this delightful short documentary, an Itali..."
7551,s7552,Movie,What Happened to Mr. Cha?,Kim Dong-kyu,"Cha In-pyo, Cho Dal-hwan, Song Jae-ryong",South Korea,"January 1, 2021",2021,TV-MA,102 min,"Comedies, International Movies","With the peak of his career long behind him, a..."
6477,s6478,TV Show,The Idhun Chronicles,Maite Ruiz De Austri,"Michelle Jenner, Itzan Escamilla, Sergio Mur, ...",Spain,"January 8, 2021",2021,TV-14,2 Seasons,"Anime Series, International TV Shows, Spanish-...",A boy suddenly orphaned fights his parents' ki...
1285,s1286,Movie,Charming,Ross Venokur,"Wilmer Valderrama, Demi Lovato, Sia, Nia Varda...","Canada, United States, Cayman Islands","January 8, 2021",2021,TV-Y7,85 min,"Children & Family Movies, Comedies","On the eve of his 21st birthday, an adored pri..."

Data Analysis

In [10]:
print(new_nf.release_year.unique())
print(new_nf.release_year.nunique())
print(new_nf.release_year.mode())
new_nf.loc[new_nf.release_year == 2017]

[1942 1944 1945 1946 1947 1954 1955 1956 1958 1959 1960 1962 1963 1964
 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974 1975 1976 1977 1978
 1979 1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991 1992
 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006
 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020
 2021]
71
0    2017
dtype: int64

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
4091,s4092,Movie,Mike Birbiglia: Thank God for Jokes,"Seth Barrish, Mike Birbiglia",Mike Birbiglia,United States,"February 28, 2017",2017,TV-MA,71 min,Stand-Up Comedy,Comedian Mike Birbiglia takes the stage in Bro...
254,s255,Movie,A Witches' Ball,Justin G. Dyck,"Morgan Neundorf, Karen Slater, Loukia Ioannou,...",Canada,"October 1, 2018",2017,PG,91 min,Children & Family Movies,"Beatrix can't wait to be inducted as a witch, ..."
3448,s3449,Movie,Krish Trish and Baltiboy: Face Your Fears,Tilak Shetty,"Tarun Ratnani, Smita Malhotra, Deepak Chachra",India,"November 17, 2017",2017,TV-Y7,65 min,Children & Family Movies,"In three tales about fear, a baby elephant get..."
4067,s4068,Movie,"Michael Bolton's Big, Sexy Valentine's Day Spe...","Scott Aukerman, Akiva Schaffer","Michael Bolton, Andy Samberg, Will Forte, Kenn...",United States,"February 7, 2017",2017,TV-MA,54 min,"Comedies, Music & Musicals, Romantic Movies","After Santa tells him he needs 75,000 new babi..."
1014,s1015,Movie,Bobbi Jene,Elvira Lind,Bobbi Jene Smith,"Denmark, Sweden, Israel, United States","June 1, 2018",2017,TV-MA,99 min,Documentaries,This candid profile follows dancer Bobbi Jene ...
...,...,...,...,...,...,...,...,...,...,...,...,...
4117,s4118,Movie,Minnaminugu the FireFly,Anil Thomas,"Surabhi Lakshmi, Krishnan Balakrishnan, Rebecc...",India,"August 1, 2018",2017,TV-14,128 min,"Dramas, International Movies",A nameless widow juggles multiple jobs to supp...
1027,s1028,Movie,Bokeh,"Geoffrey Orthwein, Andrew Sullivan","Maika Monroe, Matt O'Leary, Arnar Jónsson, Gun...","United States, Iceland","June 22, 2017",2017,TV-14,92 min,"Dramas, Independent Movies, Sci-Fi & Fantasy",After learning they are the sole survivors of ...
4108,s4109,Movie,Mindhorn,Sean Foley,"Julian Barratt, Andrea Riseborough, Essie Davi...",United Kingdom,"May 12, 2017",2017,TV-MA,88 min,"Comedies, Cult Movies, Independent Movies",When a twisted killer tells the police he'll o...
4107,s4108,Movie,MindGamers,Andrew Goth,"Tom Payne, Melia Kreiling, Antonia Campbell-Hu...",Austria,"January 15, 2020",2017,R,99 min,"International Movies, Sci-Fi & Fantasy, Thrillers",Brilliant young students discover a breakthrou...
4096,s4097,Movie,Milada,David Mrnka,"Ayelet Zurer, Robert Gant, Vica Kerekes, Aňa G...","Czech Republic, United States","January 12, 2018",2017,TV-14,124 min,"Dramas, International Movies",Politician and human rights campaigner Milada ...

In [11]:
print(new_nf.title.describe())
print(new_nf.title.unique())

count     4808
unique    4808
top       Anon
freq         1
Name: title, dtype: object
['The Battle of Midway' 'Tunisian Victory' 'Know Your Enemy - Japan' ...
 'What Happened to Mr. Cha?' 'The Idhun Chronicles' 'Charming']

In [12]:
print(new_nf.type.describe())

print(new_nf.type.unique())

count      4808
unique        2
top       Movie
freq       4673
Name: type, dtype: object
['Movie' 'TV Show']

In [13]:
print(new_nf.rating.describe())
print(new_nf.rating.unique())

count      4808
unique       14
top       TV-MA
freq       1665
Name: rating, dtype: object
['TV-14' 'TV-PG' 'TV-G' 'PG-13' 'G' 'NR' 'R' 'TV-MA' 'PG' 'UR' 'TV-Y'
 'TV-Y7' 'TV-Y7-FV' 'NC-17']

In [14]:
new_nf.director.unique()
new_nf.director.describe()

count                       4808
unique                      3613
top       Raúl Campos, Jan Suter
freq                          18
Name: director, dtype: object

In [19]:
new_nf.cast.unique()
new_nf.cast.describe()

count            4808
unique           4688
top       Samuel West
freq               10
Name: cast, dtype: object

In [20]:
new_nf.listed_in.describe()

count                             4808
unique                             323
top       Dramas, International Movies
freq                               306
Name: listed_in, dtype: object